import axios from 'axios'

export async function blackbox(prompt) {
    /*
    * source: https://whatsapp.com/channel/0029VaZSdai5Ui2TMoNsYo0J
    * scrape blackbox modal chat ai 😱
    */
    return new Promise(async (resolve, reject) => {
        const url = 'https://www.blackbox.ai/api/chat'
        const data = {
            "messages": [
                { "role": "user", "content": prompt, "id": "QgaYVnl" }
            ],
            "id": "ugrC6k4",
            "previewToken": null,
            "userId": null,
            "codeModelMode": true,
            "agentMode": {},
            "trendingAgentMode": {},
            "isMicMode": false,
            "userSystemPrompt": null,
            "maxTokens": 1024,
            "playgroundTopP": 0.9,
            "playgroundTemperature": 0.5,
            "isChromeExt": false,
            "githubToken": "",
            "clickedAnswer2": false,
            "clickedAnswer3": false,
            "clickedForceWebSearch": false,
            "visitFromDelta": false,
            "mobileClient": false,
            "userSelectedModel": null,
            "validated": "00f37b34-a166-4efb-bce5-1312d87f2f94"
        }

        const headers = {
            'Content-Type': 'application/json'
        }

        try {
            const response = await axios.post(url, data, { headers })
            let result = response.data
            result = result.replace("Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").trim()
            resolve(result)
        } catch (error) {
            reject(error)
        }
    })
}