import axios from 'axios'

async function blackbox(prompt: string): Promise<string> {
    const url = 'https://www.blackbox.ai/api/chat'
    const data = {
        messages: [
            { role: "user", content: prompt, id: "QgaYVnl" }
        ],
        id: "ugrC6k4",
        maxTokens: 1024,
        playgroundTopP: 0.9,
        playgroundTemperature: 0.5
    }

    const headers = {
        'Content-Type': 'application/json'
    }

    try {
        const response = await axios.post(url, data, { headers })
        let result = response.data
        return result.replace("Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").trim()
    } catch (error) {
        throw new Error(error)
    }
}

export { blackbox }